
import { Slide, SlideLayout, Presentation } from './types';

export const getInitialSlides = (): Slide[] => [
  {
    id: `slide-${Date.now()}-1`,
    layout: SlideLayout.TITLE,
    title: 'STEM Robotics & AI',
    subtitle: 'Building the Future with Intelligent Machines',
    content: [],
    notes: 'Welcome to the robotic masterclass. Today we explore the convergence of hardware logic and autonomous intelligence.',
    background: 'bg-gradient-to-br from-blue-900 via-indigo-800 to-purple-900',
    animation: 'fade',
    titleSize: 72,
    bodySize: 30,
    fontWeight: 'black',
    letterSpacing: -2,
    contentScale: 1.0,
    fontFamily: 'font-sans',
    lineHeight: 'normal',
    titleAlign: 'center',
    subtitleAlign: 'center',
    order: 0,
    showSlideNumber: true,
    slideNumberPosition: 'bottom-right',
    slideNumberFormat: 'prefix',
    showBanner: false,
    bannerHeight: 60,
    bannerOpacity: 100
  },
  {
    id: `slide-${Date.now()}-spec`,
    layout: SlideLayout.SPEC,
    title: 'Hardware Payload',
    subtitle: 'Current Component Configuration',
    content: [
      { id: 'sp1', type: 'spec-item', label: 'ACTUATORS', value: '4x BLDC 250W' },
      { id: 'sp2', type: 'spec-item', label: 'AUTONOMY', value: 'Jetson Orin 64G' },
      { id: 'sp3', type: 'spec-item', label: 'POWER', value: 'LiFePO4 48V 100A' },
      { id: 'sp4', type: 'spec-item', label: 'SENSORS', value: 'Solid State LiDAR' },
      { id: 'sp5', type: 'spec-item', label: 'LATENCY', value: '5ms Real-time' },
    ],
    notes: 'This module showcases the current hardware configuration. Notice the BLDC actuators provide 1KW of total output power.',
    background: 'bg-gradient-to-br from-slate-900 to-slate-800',
    animation: 'zoom',
    titleSize: 48,
    bodySize: 24,
    fontWeight: 'bold',
    letterSpacing: 0,
    contentScale: 1.0,
    fontFamily: 'font-sans',
    lineHeight: 'normal',
    titleAlign: 'left',
    subtitleAlign: 'left',
    order: 1,
    showSlideNumber: true,
    slideNumberPosition: 'bottom-right',
    slideNumberFormat: 'prefix',
    showBanner: false,
    bannerHeight: 60,
    bannerOpacity: 100
  },
  {
    id: `slide-${Date.now()}-2`,
    layout: SlideLayout.CONTENT,
    title: 'Operational Pillars',
    subtitle: 'Structural Foundation',
    content: [
      { id: 'c1', type: 'bullet', value: 'Sensors and Actuators' },
      { id: 'c2', type: 'bullet', value: 'Control Theory & Feedback Loops' },
      { id: 'c3', type: 'bullet', value: 'Machine Learning Models' },
      { id: 'c4', type: 'bullet', value: 'Real-time Operating Systems' },
    ],
    notes: 'The four operational pillars are the bedrock of modern robotics.',
    background: 'bg-gradient-to-br from-blue-900 via-indigo-800 to-purple-900',
    animation: 'slide-right',
    titleSize: 48,
    bodySize: 24,
    fontWeight: 'normal',
    letterSpacing: 0,
    contentScale: 1.0,
    fontFamily: 'font-sans',
    lineHeight: 'normal',
    titleAlign: 'left',
    subtitleAlign: 'left',
    order: 2,
    showSlideNumber: true,
    slideNumberPosition: 'bottom-right',
    slideNumberFormat: 'fraction',
    showBanner: false,
    bannerHeight: 60,
    bannerOpacity: 100
  }
];

export const createNewPresentation = (title = 'New Robotics Deck'): Presentation => ({
  id: `deck-${Math.random().toString(36).substr(2, 9)}-${Date.now()}`,
  title,
  subtitle: 'Fall 2024 Series',
  aspectRatio: '16:9',
  slides: getInitialSlides(),
  createdAt: new Date().toLocaleString(),
  updatedAt: new Date().toLocaleString(),
  author: 'STEM Master',
});

export const INITIAL_PRESENTATION = createNewPresentation('Robotics Masterclass');
